/** `@studio/core` — public API surface (SPEC §1.1). Everything else is internal. */
export * as schema from './db/schema'
export { createDb, type Db } from './db/client'
export { env, envKeys, envSchema, isStudioHost, optionalEnvKeys, parseEnv, requiredEnvKeys, type Env } from './env'
export { createSite, type RouteContext, type RouteHandler, type Site, type SiteHandlers } from './handlers/index'
export type { HandlerDeps } from './handlers/context'
export { noCache, type Cache } from './cache'
export { CONTENT_REVALIDATE_SECONDS, type Content, type ListOptions } from './content/index'
export { mediaUrl } from './storage/url'
export { defineCollection, defineCollections } from './collections/define'
export { defaultCollections, pickCollections } from './collections/defaults'
export type { Collection, CollectionConfig, CollectionMap, CollectionMeta, Collections, Doc, Field, FieldType, ListConfig, ReadsConfig } from './collections/types'
export { RichText } from './richtext/render'
export { docFromText, docToText, richTextDocSchema } from './richtext/schema'
export { EMPTY_DOC, type RichTextDoc } from './richtext/types'
export { sendMail } from './email/send'
export { memoryMailer, type Mailer, type MailMessage } from './email/mailer'
export { formSchemas } from './handlers/forms'
export type { Donation, Event, Media, Page, Post, Settings, Submission } from './db/schema'
