// Generated by `pnpm scaffold` — do not edit. A plain, factual notice; not legal advice.
import type { Metadata } from 'next'
import { PageHeader, Prose } from '@/components/sections'
import { site } from '@/lib/site'

export const metadata: Metadata = { title: 'Privacy', description: "How Christy Eller Design handles the information this website collects." }

export default function Page() {
  return (
    <>
      <PageHeader title="Privacy" body="What this website collects, and what happens to it." />
      <Prose>
        <p>When you use the contact form, we receive what you type — typically your name, email address and message — and it is emailed to us and stored so we can reply. We use it for nothing else, and we never sell or share it.</p>
        
        <p>This site does not use advertising, tracking cookies, or sell data to anyone. Hosting providers keep ordinary technical logs (such as IP addresses) to run the service securely.</p>
        <p>To ask about, correct, or delete information we hold about you, email <a href={`mailto:${site.brief.contact.email}`}>{site.brief.contact.email}</a>.</p>
      </Prose>
    </>
  )
}
