// Generated by `pnpm scaffold` from brief.json — do not edit. Sites may remove collections, never add (SPEC §6).
import { defaultCollections, defineCollections, pickCollections } from '@studio/core'
import { site } from './site'

const ENABLED = ['pages', 'posts', 'events', 'media', 'submissions', 'settings'] as const

export const collections = defineCollections(
  pickCollections(defaultCollections({ timezone: site.timezone }), [...ENABLED]),
)
