// Drives the admin end to end against the local smoke site and saves screenshots.
// usage: node admin-shots.mjs <base> <verify-token> <outdir>
import { chromium } from '@playwright/test'
import fs from 'node:fs'

const [base, token, out] = process.argv.slice(2)
fs.mkdirSync(out, { recursive: true })
const browser = await chromium.launch()
const ctx = await browser.newContext({ viewport: { width: 1280, height: 860 } })
const page = await ctx.newPage()
const errors = []
page.on('pageerror', (e) => errors.push(`pageerror: ${e.message}`))
page.on('console', (m) => m.type() === 'error' && errors.push(`console: ${m.text()}`))
const shot = async (name) => page.screenshot({ path: `${out}/${name}.png`, fullPage: true })
const settle = () => page.waitForTimeout(700)
const fail = async (e) => { errors.push(`fatal: ${e.message}`); await shot('zz-failure').catch(() => {}); const toasts = await page.locator('[data-sonner-toast]').allTextContents().catch(() => []); console.log(JSON.stringify({ errors, toasts, url: page.url(), api: apiLog.slice(-8) }, null, 1)); process.exit(1) }
process.on('unhandledRejection', fail); process.on('uncaughtException', fail)
const apiLog = []
page.on('response', (r) => { if (r.url().includes('/api/site/')) apiLog.push(`${r.request().method()} ${r.url().replace(base, '')} ${r.status()}`) })

await page.goto(`${base}/admin`)
await shot('00-login')
await page.goto(`${base}/api/site/auth/verify?token=${token}`)
await page.waitForURL(/\/admin/)
await page.waitForSelector('[data-admin=cards]')
await settle()
await shot('01-home')

// Messages: list → open (auto-marks read) → back
await page.click('[data-admin=nav] a:has-text("Messages")')
await page.waitForSelector('[data-admin=table], [data-admin=empty]')
await settle()
await shot('02-messages')
const unreadBefore = await page.locator('[data-admin=nav] [data-admin=badge]').textContent().catch(() => null)
await page.click('[data-admin=table] tr[data-row] >> nth=0')
await page.waitForSelector('[data-admin=message]')
await settle()
await shot('03-message')
const unreadAfter = await page.locator('[data-admin=nav] [data-admin=badge]').textContent().catch(() => null)

// Photos grid
await page.click('[data-admin=nav] a:has-text("Photos")')
await page.waitForSelector('[data-admin=tiles], [data-admin=empty]')
await settle()
await shot('04-photos')
// inline description edit on the first tile
const alt = page.locator('[data-admin=tile] [data-admin=alt]').first()
const before = await alt.inputValue()
await alt.fill((before ? before + ' (edited)' : 'A photo of the place').slice(0, 200))
await alt.press('Enter')
await page.waitForSelector('[data-admin=tile] [data-admin=saved]:has-text("Saved")', { timeout: 5000 }).catch(() => errors.push('alt inline save: no "Saved" shown'))

// News: new post → publish → edit → view on site link
await page.click('[data-admin=nav] a:has-text("News")')
await page.waitForSelector('[data-admin=table], [data-admin=empty]')
await settle()
await shot('05-news')
await page.click('button:has-text("New post")')
await page.waitForSelector('form[data-admin=form]')
await settle()
await shot('06-new-post')
await page.fill('#f-title', 'Admin redesign check')
await page.fill('#f-excerpt', 'Written by the verification script.')
await page.click('[data-admin=editor] .tiptap')
await page.keyboard.type('Body text typed into the editor. ')
await page.click('[data-admin=toolbar] button[aria-label="Link"]')
await page.fill('[data-admin=linkbar] input', 'https://example.org')
await page.click('[data-admin=linkbar] button:has-text("Apply")')
await shot('07-new-post-filled')
await page.click('[data-admin=publish] button:has-text("Publish")')
await page.waitForSelector('[data-sonner-toast]:has-text("Published")', { timeout: 8000 })
await page.waitForURL(/\/admin\/posts\/[0-9a-f-]{36}$/)
await settle()
await shot('08-published')
const viewLink = await page.locator('a:has-text("View on site")').getAttribute('href').catch(() => null)
const toastLink = await page.locator('[data-sonner-toast] button:has-text("View")').count().then((n) => (n ? 'action' : null)).catch(() => null)
// dirty guard: every way out of an edited form is refused with a "Discard them" toast — Back and the sidebar alike.
await page.fill('#f-title', 'Admin redesign check (edited)')
await page.click('button:has-text("Back")')
await page.click('[data-admin=nav] a:has-text("Photos")')
const guarded = (await page.locator('[data-sonner-toast]:has-text("unsaved")').count()) > 0 && page.url().includes('/admin/posts/')
await shot('08b-dirty-guard')
await page.click('button:has-text("Save changes")')
await page.waitForSelector('[data-sonner-toast]:has-text("Saved")', { timeout: 8000 })
await page.click('button:has-text("Unpublish")')
await page.waitForSelector('[data-sonner-toast]:has-text("Unpublished")', { timeout: 8000 })
await settle()
await shot('09-unpublished')
// delete two-step
await page.click('form[data-admin=form] button:has-text("Delete")')
await page.waitForSelector('button:has-text("Really delete?")')
await shot('09b-really-delete')
await page.click('button:has-text("Really delete?")')
await page.waitForSelector('[data-sonner-toast]:has-text("deleted")', { timeout: 8000 }).catch(async () => { await shot('09c-delete-failed'); errors.push('delete: no toast') })
await page.waitForURL(/\/admin\/posts$/, { timeout: 8000 }).catch(() => errors.push('delete: did not return to list'))

// Settings: the singleton opens as a form; a change shows on the public footer without a redeploy
await page.click('[data-admin=nav] a:has-text("Settings")')
await page.waitForSelector('form[data-admin=form]')
await settle()
await shot('09d-settings')
const settingsHasNoBack = (await page.locator('button:has-text("Back")').count()) === 0
await page.fill('#f-phone', '555-0142')
await page.click('button:has-text("Save")')
await page.waitForSelector('[data-sonner-toast]:has-text("Saved")', { timeout: 8000 })
const footerPhone = await fetch(`${base}/`).then((r) => r.text()).then((h) => h.includes('555-0142')).catch(() => false)

// Pages: create, publish with "Show in the menu", it appears in the site nav and at /<slug>
await page.click('[data-admin=nav] a:has-text("Pages")')
await page.waitForSelector('[data-admin=table], [data-admin=empty]')
await page.click('button:has-text("New page")')
await page.waitForSelector('form[data-admin=form]')
await page.fill('#f-title', 'Our story')
await page.click('[data-admin=editor] .tiptap')
await page.keyboard.type('A page written by the verification script.')
await page.click('#f-showInNav')
await page.click('[data-admin=publish] button:has-text("Publish")')
await page.waitForSelector('[data-sonner-toast]:has-text("Published")', { timeout: 8000 })
await settle()
await shot('09e-page-published')
const pageHtml = await fetch(`${base}/our-story`).then((r) => (r.ok ? r.text() : '')).catch(() => '')
const pageLive = pageHtml.includes('A page written by the verification script')
const navHasPage = await fetch(`${base}/`).then((r) => r.text()).then((h) => h.includes('href="/our-story"')).catch(() => false)

// mobile
await page.setViewportSize({ width: 390, height: 844 })
await page.goto(`${base}/admin`)
await page.waitForSelector('[data-admin=cards]')
await settle()
await shot('10-mobile-home')
await page.click('[data-admin=top] button:has-text("Menu")')
await settle()
await shot('11-mobile-menu')
await page.click('[role=dialog] [data-admin=nav] a:has-text("Messages")')
await page.waitForSelector('[data-admin=table], [data-admin=empty]')
await settle()
await shot('12-mobile-messages')

await browser.close()
console.log(JSON.stringify({ unreadBefore, unreadAfter, viewLink, toastLink, dirtyGuard: guarded, settingsHasNoBack, footerPhone, pageLive, navHasPage, errors }, null, 1))
