// Generated by `pnpm scaffold` — do not edit. Shown once the owner adds events in the admin.
import type { Metadata } from 'next'
import { EventList, PageHeader } from '@/components/sections'

export const metadata: Metadata = { title: 'Events', description: "What's coming up at Christy Eller Design." }

export default function Page() {
  return (
    <>
      <PageHeader title="Events" body="What's coming up at Christy Eller Design." />
      <EventList title="Upcoming" limit={24} />
    </>
  )
}
