/**
 * `pnpm scaffold` — deterministic generation from brief.json + the chosen direction.
 * Protected files are always rewritten; page files are written only when missing (or with --force),
 * because pages are where the model does its work.
 */
import fs from 'node:fs'
import path from 'node:path'
import { briefSchema, type Brief, type PageKey } from '../lib/brief'

const ROOT = path.resolve(import.meta.dirname, '..')
const force = process.argv.includes('--force')
const q = (s: string) => JSON.stringify(s)

function read(): Brief {
  const raw = JSON.parse(fs.readFileSync(path.join(ROOT, 'brief.json'), 'utf8')) as unknown
  const r = briefSchema.safeParse(raw)
  if (!r.success) {
    console.error('brief.json is invalid:')
    for (const i of r.error.issues) console.error(`  ${i.path.join('.') || '(root)'}: ${i.message}`)
    process.exit(1)
  }
  return r.data
}

function write(rel: string, content: string, { protect }: { protect: boolean }): void {
  const file = path.join(ROOT, rel)
  if (!protect && fs.existsSync(file) && !force) {
    console.log(`  keep     ${rel}`)
    return
  }
  fs.mkdirSync(path.dirname(file), { recursive: true })
  fs.writeFileSync(file, content.trimStart())
  console.log(`  ${protect ? 'generate' : 'create  '} ${rel}`)
}

const firstSentence = (s: string) => (s.match(/^[^.!?]+[.!?]/)?.[0] ?? s).trim()
const trunc = (s: string, n: number) => (s.length <= n ? s : s.slice(0, n - 1).replace(/\s+\S*$/, '') + '…')
const heroBody = (b: Brief) => trunc(firstSentence(b.org.mission), 180)
const metaDesc = (b: Brief, s = b.org.mission) => trunc(s.replace(/\s+/g, ' '), 158)

/* ---------- generated files ---------- */

function activeTs(b: Brief): string {
  return `// Generated by \`pnpm scaffold\` from brief.json — do not edit.
export { active } from './directions/${b.direction}'
`
}

function collectionsTs(b: Brief): string {
  const f = b.features
  // Nav order. Pages and settings are on every site: they are how an owner changes things without a rebuild.
  const enabled = ['pages']
  if (f.posts) enabled.push('posts')
  if (f.events) enabled.push('events')
  enabled.push('media')
  if (f.contactForm || f.volunteerForm || f.newsletter) enabled.push('submissions')
  if (f.donations) enabled.push('donations')
  enabled.push('settings')
  return `// Generated by \`pnpm scaffold\` from brief.json — do not edit. Sites may remove collections, never add (SPEC §6).
import { defaultCollections, defineCollections, pickCollections } from '@studio/core'
import { site } from './site'

const ENABLED = ${JSON.stringify(enabled)} as const

export const collections = defineCollections(pickCollections(defaultCollections({ timezone: site.timezone }), [...ENABLED]))
`
}

interface DirectionMeta {
  composition: { heroVariants: string[]; maxColumns: number }
}

function pageFile(b: Brief, key: PageKey, dir: DirectionMeta): string {
  const heroVariant = dir.composition.heroVariants[0] ?? 'photo'
  const cols = dir.composition.maxColumns >= 3 ? 3 : 2
  const ctas = (b.copy.callsToAction ?? []).slice(0, 2)
  const has = (k: PageKey) => b.pages.includes(k)
  const landscape = [...b.media.photos].sort((x, y) => y.width / y.height - x.width / x.height)
  const photo = (i: number) => landscape[i % Math.max(1, landscape.length)]
  const photoExpr = (i: number) => (landscape.length ? `site.photo(${q(photo(i)!.key)})` : undefined)
  const cta = (i: number) => (ctas[i] ? `{ label: ${q(ctas[i]!)}, href: site.ctas[${i}]!.href }` : undefined)
  const name = b.org.name
  const t = b.copy.testimonials ?? []
  const imports = new Set<string>()
  const use = (s: string) => (imports.add(s), s)

  let title = ''
  let desc = ''
  const body: string[] = []

  switch (key) {
    case 'home': {
      title = b.org.tagline
      desc = metaDesc(b)
      const heroHasPhoto = heroVariant === 'photo' && Boolean(photoExpr(0))
      body.push(`<${use('Hero')} variant=${q(heroVariant)} eyebrow=${q(name)} title=${q(b.org.tagline)} body=${q(heroBody(b))}${cta(0) ? ` cta={${cta(0)}}` : ''}${cta(1) ? ` secondaryCta={${cta(1)}}` : ''}${heroHasPhoto ? ` photo={${photoExpr(0)}}` : ''} />`)
      body.push(`<${use('FeatureGrid')} title=${q(`Why ${name}`)} columns={${cols}} items={${JSON.stringify(b.copy.keyMessages.map((m) => ({ title: m, body: '' })))}} />`)
      // A direction that leads with text still gets the best photo, just lower down.
      if (!heroHasPhoto && photoExpr(0) && b.org.about) body.push(`<${use('PhotoText')} title=${q(`About ${name}`)} body={${JSON.stringify(b.org.about.split(/\n\s*\n/).slice(0, 2))}} photo={${photoExpr(0)}} align="right" />`)
      if (has('events') && b.features.events) body.push(`<${use('EventList')} title="Coming up" limit={3} tone=${heroHasPhoto ? '"surface"' : '"bg"'} />`)
      else if (has('posts') && b.features.posts) body.push(`<${use('PostList')} title="Latest news" limit={3} tone="surface" />`)
      else if (heroHasPhoto && photoExpr(1) && b.org.about) body.push(`<${use('PhotoText')} title=${q(`About ${name}`)} body={${JSON.stringify(b.org.about.split(/\n\s*\n/).slice(0, 2))}} photo={${photoExpr(1)}} align="right" />`)
      if (t.length) body.push(`<${use('Testimonials')} items={${JSON.stringify(t)}} />`)
      if (cta(0)) body.push(`<${use('CTA')} title=${q(b.copy.keyMessages[0]!)}${b.copy.keyMessages[1] ? ` body=${q(b.copy.keyMessages[1])}` : ''} cta={${cta(0)}}${cta(1) ? ` secondaryCta={${cta(1)}}` : ''} />`)
      break
    }
    case 'about': {
      title = `About ${name}`
      desc = metaDesc(b, b.org.about ?? b.org.mission)
      body.push(`<${use('PageHeader')} eyebrow="About" title=${q(`About ${name}`)} body=${q(heroBody(b))} />`)
      const paras = (b.org.about ?? b.org.mission).split(/\n\s*\n/).map((p) => p.trim()).filter(Boolean)
      body.push(`<${use('Prose')} title="Our mission">\n${paras.map((p) => `        <p>${escapeJsx(p)}</p>`).join('\n')}\n      </Prose>`)
      if (photoExpr(1)) body.push(`<${use('PhotoText')} title=${q(b.org.tagline)} body=${q(trunc(b.copy.audience, 240))} photo={${photoExpr(1)}} />`)
      body.push(`<${use('FeatureGrid')} title="What matters to us" columns={${cols}} items={${JSON.stringify(b.copy.keyMessages.map((m) => ({ title: m, body: '' })))}} />`)
      if (cta(0)) body.push(`<${use('CTA')} title=${q('Come and see for yourself')} cta={${cta(0)}} variant="card" />`)
      break
    }
    case 'events': {
      title = 'Events'
      desc = `Upcoming events at ${name}. ${trunc(firstSentence(b.org.mission), 100)}`
      body.push(`<${use('PageHeader')} title="Events" body=${q(`What's coming up at ${name}.`)} />`)
      body.push(`<${use('EventList')} title="Upcoming" limit={24} />`)
      if (cta(0)) body.push(`<${use('CTA')} title="Want to be part of it?" cta={${cta(0)}} />`)
      break
    }
    case 'posts': {
      title = 'News'
      desc = `News and updates from ${name}.`
      body.push(`<${use('PageHeader')} title="News" body=${q(`Updates from ${name}.`)} />`)
      body.push(`<${use('PostList')} title="Latest" limit={24} />`)
      break
    }
    case 'gallery': {
      title = 'Gallery'
      desc = `Photos from ${name}.`
      body.push(`<${use('PageHeader')} title="Gallery" body=${q(`A look around ${name}.`)} />`)
      const cols = b.seed.galleryCollections ?? []
      if (cols.length) for (const c of cols) body.push(`<${use('Gallery')} collection=${q(c.name)} title=${q(c.title ?? c.name)} />`)
      else body.push(`<${use('Gallery')} collection="gallery" title="Photos" />`)
      break
    }
    case 'donate': {
      title = `Give to ${name}`
      desc = `Support the work of ${name}. ${trunc(firstSentence(b.org.mission), 100)}`
      body.push(`<${use('PageHeader')} title="Give" body=${q(`Your gift supports ${name}.`)} />`)
      body.push(`<${use('DonationBlock')} title="Make a gift" body=${q(trunc(firstSentence(b.org.mission), 160))} configured={Boolean(process.env['STRIPE_SECRET_KEY'])} />`)
      if (t.length) body.push(`<${use('Testimonials')} items={${JSON.stringify(t.slice(0, 2))}} />`)
      break
    }
    case 'contact': {
      title = 'Contact'
      desc = `Get in touch with ${name}. ${b.contact.address ? `${b.contact.address.street}, ${b.contact.address.city}.` : ''}`.trim()
      body.push(`<${use('PageHeader')} title="Contact" body=${q(`We'd love to hear from you.`)} />`)
      body.push(`<${use('ContactDetails')} />`)
      if (b.features.contactForm) body.push(`<${use('ContactForm')} variant="contact" title="Send a message" />`)
      if (b.features.newsletter) body.push(`<${use('ContactForm')} variant="newsletter" title="Get our updates" tone="surface" />`)
      body.push(`<${use('Map')} />`)
      break
    }
    case 'volunteer': {
      title = 'Volunteer'
      desc = `Volunteer with ${name}. ${trunc(firstSentence(b.copy.audience), 100)}`
      body.push(`<${use('PageHeader')} title="Volunteer" body=${q(`There's a place for you at ${name}.`)} />`)
      body.push(`<${use('FeatureGrid')} title="Ways to help" columns={${cols}} items={${JSON.stringify(b.copy.keyMessages.map((m) => ({ title: m, body: '' })))}} />`)
      body.push(`<${use('ContactForm')} variant="volunteer" />`)
      break
    }
  }

  const usesSite = body.some((l) => l.includes('site.'))
  return `import type { Metadata } from 'next'
import { ${[...imports].sort().join(', ')} } from '@/components/sections'
${usesSite ? "import { site } from '@/lib/site'\n" : ''}
export const metadata: Metadata = { title: ${q(trunc(title, 60))}, description: ${q(desc)} }

export default function Page() {
  return (
    <>
      ${body.join('\n      ')}
    </>
  )
}
`
}

function escapeJsx(s: string): string {
  return s.replace(/[{}<>]/g, (c) => ({ '{': '&#123;', '}': '&#125;', '<': '&lt;', '>': '&gt;' })[c]!).replace(/'/g, '’')
}

function privacyPage(b: Brief): string {
  const forms: string[] = []
  if (b.features.contactForm) forms.push('the contact form')
  if (b.features.volunteerForm) forms.push('the volunteer form')
  if (b.features.newsletter) forms.push('the newsletter sign-up')
  return `// Generated by \`pnpm scaffold\` — do not edit. A plain, factual notice; not legal advice.
import type { Metadata } from 'next'
import { PageHeader, Prose } from '@/components/sections'
import { site } from '@/lib/site'

export const metadata: Metadata = { title: 'Privacy', description: ${q(`How ${b.org.name} handles the information this website collects.`)} }

export default function Page() {
  return (
    <>
      <PageHeader title="Privacy" body="What this website collects, and what happens to it." />
      <Prose>
        ${forms.length ? `<p>When you use ${escapeJsx(forms.join(', '))}, we receive what you type — typically your name, email address and message — and it is emailed to us and stored so we can reply. We use it for nothing else, and we never sell or share it.</p>` : `<p>This website has no forms and collects no personal information from visitors.</p>`}
        ${b.features.donations ? `<p>Online donations are processed by Stripe; your card details go directly to Stripe and never touch this website. We keep a record of the donation itself (amount, date, and the name and email you provide) for receipts and bookkeeping.</p>` : ''}
        <p>This site does not use advertising, tracking cookies, or sell data to anyone. Hosting providers keep ordinary technical logs (such as IP addresses) to run the service securely.</p>
        <p>To ask about, correct, or delete information we hold about you, email <a href={\`mailto:\${site.brief.contact.email}\`}>{site.brief.contact.email}</a>.</p>
      </Prose>
    </>
  )
}
`
}

const postPage = `// Generated by \`pnpm scaffold\` — do not edit.
import type { Metadata } from 'next'
import { notFound } from 'next/navigation'
import { JsonLd, PageHeader, Photo, Prose } from '@/components/sections'
import { Container, Section } from '@/components/ui'
import { content } from '@/lib/core'
import { formatDate } from '@/lib/format'
import { site } from '@/lib/site'

type Params = { params: Promise<{ slug: string }> }

export async function generateStaticParams() {
  return (await content.list('posts', { limit: 200 })).map((p) => ({ slug: p.slug }))
}

export async function generateMetadata({ params }: Params): Promise<Metadata> {
  const post = await content.get('posts', (await params).slug)
  if (!post) return {}
  return { title: post.title, description: post.excerpt ?? undefined, alternates: { canonical: \`/posts/\${post.slug}\` } }
}

export default async function PostPage({ params }: Params) {
  const post = await content.get('posts', (await params).slug)
  if (!post) notFound()
  const cover = post.cover && post.cover.width && post.cover.height ? { key: post.cover.key, width: post.cover.width, height: post.cover.height, alt: post.cover.alt } : null
  return (
    <>
      <PageHeader eyebrow={post.publishedAt ? formatDate(post.publishedAt) : undefined} title={post.title} body={post.excerpt ?? undefined} />
      {cover && (
        <Section className="!pb-0">
          <Container narrow>
            <Photo photo={cover} priority sizes="(min-width: 768px) 768px, 100vw" />
          </Container>
        </Section>
      )}
      <Prose doc={post.body} />
      <JsonLd
        data={{
          '@context': 'https://schema.org',
          '@type': 'Article',
          headline: post.title,
          datePublished: post.publishedAt?.toISOString(),
          dateModified: post.updatedAt.toISOString(),
          author: { '@type': 'Organization', name: site.name },
          publisher: { '@type': 'Organization', name: site.name },
          mainEntityOfPage: \`\${site.url}/posts/\${post.slug}\`,
        }}
      />
    </>
  )
}
`

const eventPage = `// Generated by \`pnpm scaffold\` — do not edit.
import type { Metadata } from 'next'
import { notFound } from 'next/navigation'
import { JsonLd, PageHeader, Photo, Prose } from '@/components/sections'
import { ButtonLink, Container, Section } from '@/components/ui'
import { content } from '@/lib/core'
import { formatEventRange } from '@/lib/format'
import { site } from '@/lib/site'

type Params = { params: Promise<{ slug: string }> }

export async function generateStaticParams() {
  return (await content.list('events', { limit: 200 })).map((e) => ({ slug: e.slug }))
}

export async function generateMetadata({ params }: Params): Promise<Metadata> {
  const ev = await content.get('events', (await params).slug)
  if (!ev) return {}
  return { title: ev.title, description: \`\${formatEventRange(ev.startsAt, ev.endsAt, ev.timezone)}\${ev.location ? \` · \${ev.location}\` : ''}\`, alternates: { canonical: \`/events/\${ev.slug}\` } }
}

export default async function EventPage({ params }: Params) {
  const ev = await content.get('events', (await params).slug)
  if (!ev) notFound()
  const cover = ev.cover && ev.cover.width && ev.cover.height ? { key: ev.cover.key, width: ev.cover.width, height: ev.cover.height, alt: ev.cover.alt } : null
  const when = formatEventRange(ev.startsAt, ev.endsAt, ev.timezone)
  return (
    <>
      <PageHeader eyebrow={when} title={ev.title} body={ev.location ?? undefined} />
      {cover && (
        <Section className="!pb-0">
          <Container narrow>
            <Photo photo={cover} priority sizes="(min-width: 768px) 768px, 100vw" />
          </Container>
        </Section>
      )}
      <Prose doc={ev.description} />
      {ev.url && (
        <Section className="!pt-0">
          <Container narrow>
            <ButtonLink href={ev.url}>More about this event</ButtonLink>
          </Container>
        </Section>
      )}
      <JsonLd
        data={{
          '@context': 'https://schema.org',
          '@type': 'Event',
          name: ev.title,
          startDate: ev.startsAt.toISOString(),
          ...(ev.endsAt ? { endDate: ev.endsAt.toISOString() } : {}),
          ...(ev.location ? { location: { '@type': 'Place', name: ev.location } } : {}),
          url: \`\${site.url}/events/\${ev.slug}\`,
          organizer: { '@type': 'Organization', name: site.name, url: site.url },
        }}
      />
    </>
  )
}
`

const pagePage = `// Generated by \`pnpm scaffold\` — do not edit. Renders pages the owner adds in the admin (Pages).
import type { Metadata } from 'next'
import { notFound } from 'next/navigation'
import { PageHeader, Photo, Prose } from '@/components/sections'
import { Container, Section } from '@/components/ui'
import { content } from '@/lib/core'

type Params = { params: Promise<{ slug: string }> }

export async function generateStaticParams() {
  return (await content.list('pages', { limit: 200 })).map((p) => ({ slug: p.slug }))
}

export async function generateMetadata({ params }: Params): Promise<Metadata> {
  const page = await content.get('pages', (await params).slug)
  if (!page) return {}
  return { title: page.title, description: page.description ?? undefined, alternates: { canonical: \`/\${page.slug}\` } }
}

export default async function OwnerPage({ params }: Params) {
  const page = await content.get('pages', (await params).slug)
  if (!page) notFound()
  const cover = page.cover && page.cover.width && page.cover.height ? { key: page.cover.key, width: page.cover.width, height: page.cover.height, alt: page.cover.alt } : null
  return (
    <>
      <PageHeader title={page.title} body={page.description ?? undefined} />
      {cover && (
        <Section className="!pb-0">
          <Container narrow>
            <Photo photo={cover} priority sizes="(min-width: 768px) 768px, 100vw" />
          </Container>
        </Section>
      )}
      <Prose doc={page.body} />
    </>
  )
}
`

/* ---------- main ---------- */

const brief = read()
const dirs = fs.readdirSync(path.join(ROOT, 'design/directions')).filter((d) => fs.existsSync(path.join(ROOT, 'design/directions', d, 'direction.json')))
if (!dirs.includes(brief.direction)) {
  console.error(`Unknown direction "${brief.direction}". Available: ${dirs.join(', ')}`)
  process.exit(1)
}
console.log(`Scaffolding ${brief.org.name} (${brief.slug}) · direction ${brief.direction} · pages ${brief.pages.join(', ')}`)
write('design/active.ts', activeTs(brief), { protect: true })
write('lib/collections.ts', collectionsTs(brief), { protect: true })
const direction = JSON.parse(fs.readFileSync(path.join(ROOT, 'design/directions', brief.direction, 'direction.json'), 'utf8')) as DirectionMeta
for (const key of brief.pages) write(key === 'home' ? 'app/(site)/page.tsx' : `app/(site)/${key}/page.tsx`, pageFile(brief, key, direction), { protect: false })
write('app/(site)/privacy/page.tsx', privacyPage(brief), { protect: true })
write('app/(site)/[slug]/page.tsx', pagePage, { protect: true })
if (brief.features.posts) write('app/(site)/posts/[slug]/page.tsx', postPage, { protect: true })
else fs.rmSync(path.join(ROOT, 'app/(site)/posts/[slug]'), { recursive: true, force: true })
if (brief.features.events) write('app/(site)/events/[slug]/page.tsx', eventPage, { protect: true })
else fs.rmSync(path.join(ROOT, 'app/(site)/events/[slug]'), { recursive: true, force: true })
// Pages the brief no longer asks for are removed so the sitemap and nav stay truthful.
let removed = false
for (const key of ['about', 'events', 'posts', 'gallery', 'donate', 'contact', 'volunteer'] as PageKey[]) {
  if (!brief.pages.includes(key) && fs.existsSync(path.join(ROOT, 'app/(site)', key, 'page.tsx'))) {
    fs.rmSync(path.join(ROOT, 'app/(site)', key, 'page.tsx'))
    console.log(`  remove   app/(site)/${key}/page.tsx`)
    removed = true
  }
}
// Next's generated route validator references pages that no longer exist; drop it so typecheck is truthful.
if (removed || !brief.features.posts || !brief.features.events) fs.rmSync(path.join(ROOT, '.next/types'), { recursive: true, force: true })
console.log('done')
