import generated from './directions.generated.json'

export interface DirectionCard {
  name: string
  label: string
  summary: string
  suits: string[]
  fonts: { heading: string; body: string }
  tokens: Record<string, string>
}

/** Snapshot of template/design/directions/*, generated by scripts/gen-directions.mjs before every build. */
export function directions(): DirectionCard[] {
  return generated as DirectionCard[]
}
